
CREATE PROCEDURE create_db_constraints

AS

ALTER TABLE GAMES_GB
ADD CONSTRAINT FK_GAMES_AWAY_TEAM FOREIGN KEY (AWAY_TEAM) REFERENCES TEAMS_GB(TEAM_ID);

ALTER TABLE GAMES_GB
ADD CONSTRAINT FK_GAMES_HOME_TEAM_ID FOREIGN KEY (HOME_TEAM) REFERENCES TEAMS_GB(TEAM_ID);

ALTER TABLE GAMES_GB
ADD CONSTRAINT FK_GAMES_LOCATION FOREIGN KEY (GAME_LOCATION) REFERENCES LOCATIONS_GB(LOCATION_NAME);

ALTER TABLE TEAMS_GB
ADD CONSTRAINT FK_TEAMS_CONFERENCE FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCES_GB(CONFERENCE_ID);