

ALTER PROCEDURE create_schedule_db

AS

CREATE TABLE GAMES_GB (
	GAME_ID				TINYINT		NOT NULL	PRIMARY KEY,
	AWAY_TEAM			TINYINT		NOT NULL,
	HOME_TEAM			TINYINT		NOT NULL,
	GAME_LOCATION		VARCHAR(64) NOT NULL,
	GAME_DAY			VARCHAR(16) NULL,
	GAME_TIME			VARCHAR(16)	NULL,
	WEEK_NUM			TINYINT		NULL
);

CREATE TABLE TEAMS_GB (
	TEAM_ID				TINYINT		NOT NULL	PRIMARY KEY,
	CONFERENCE_ID		TINYINT		NOT NULL,
	SCHOOL_NAME			VARCHAR(64) NULL,
	SCHOOL_MASCOT		VARCHAR(64) NULL
);

CREATE TABLE CONFERENCES_GB (
	CONFERENCE_ID		TINYINT		NOT NULL	PRIMARY KEY,
	CONFERENCE_NAME		VARCHAR(32) NULL
);

CREATE TABLE LOCATIONS_GB (
	LOCATION_NAME		VARCHAR(64)		NOT NULL	PRIMARY KEY,
	LATITUDE			DECIMAL(8,5)	NOT NULL,
	LONGITUDE			DECIMAL(8,5)	NOT NULL,
	CITY				VARCHAR(64)		NULL,
	STATE				VARCHAR(32)		NULL
);


ALTER TABLE GAMES_GB
ADD FOREIGN KEY (AWAY_TEAM) REFERENCES TEAMS_GB(TEAM_ID);

ALTER TABLE GAMES_GB
ADD FOREIGN KEY (HOME_TEAM) REFERENCES TEAMS_GB(TEAM_ID);

ALTER TABLE GAMES_GB
ADD FOREIGN KEY (GAME_LOCATION) REFERENCES LOCATIONS_GB(LOCATION_NAME);

ALTER TABLE TEAMS_GB
ADD FOREIGN KEY (CONFERENCES_GB) REFERENCES CONFERENCES_GB(CONFERENCES_GB);


GO