
CREATE VIEW GET_ALL_GAMES_VW AS

SELECT
	G.WEEK_NUM,
	G.GAME_DAY,
	G.GAME_TIME,
	AWY.SCHOOL_NAME AS AWAY_SCHOOL,
	AWY.SCHOOL_MASCOT AS AWAY_MASCOT,
	AWY_CONF.CONFERENCE_NAME AS AWAY_CONFERENCE,
	HOM.SCHOOL_NAME AS HOME_SCHOOL,
	HOM.SCHOOL_MASCOT AS HOME_MASCOT,
	HOM_CONF.CONFERENCE_NAME AS HOME_CONFERENCE,
	G.GAME_LOCATION,
	LOC.LATITUDE,
	LOC.LONGITUDE
FROM
	GAMES_GB G
		INNER JOIN TEAMS_GB AWY
			ON G.AWAY_TEAM = AWY.TEAM_ID
		LEFT JOIN CONFERENCES_GB AWY_CONF
			ON AWY.CONFERENCE_ID = AWY_CONF.CONFERENCE_ID
		INNER JOIN TEAMS_GB HOM
			ON G.HOME_TEAM = HOM.TEAM_ID
		LEFT JOIN CONFERENCES_GB HOM_CONF
			ON HOM.CONFERENCE_ID = HOM_CONF.CONFERENCE_ID
		INNER JOIN LOCATIONS_GB LOC
			ON G.GAME_LOCATION = LOC.LOCATION_NAME;


