
CREATE PROCEDURE insert_conference_records

AS

INSERT INTO CONFERENCES_GB (CONFERENCE_ID, CONFERENCE_NAME)
    VALUES (1, 'ACC');

INSERT INTO CONFERENCES_GB (CONFERENCE_ID, CONFERENCE_NAME)
    VALUES (151, 'American');

INSERT INTO CONFERENCES_GB (CONFERENCE_ID, CONFERENCE_NAME)
    VALUES (4, 'Big 12');

INSERT INTO CONFERENCES_GB (CONFERENCE_ID, CONFERENCE_NAME)
    VALUES (5, 'Big Ten');

INSERT INTO CONFERENCES_GB (CONFERENCE_ID, CONFERENCE_NAME)
    VALUES (12, 'C-USA');

INSERT INTO CONFERENCES_GB (CONFERENCE_ID, CONFERENCE_NAME)
    VALUES (18, 'Independents');

INSERT INTO CONFERENCES_GB (CONFERENCE_ID, CONFERENCE_NAME)
    VALUES (15, 'MAC');

INSERT INTO CONFERENCES_GB (CONFERENCE_ID, CONFERENCE_NAME)
    VALUES (17, 'MWC');

INSERT INTO CONFERENCES_GB (CONFERENCE_ID, CONFERENCE_NAME)
    VALUES (9, 'PAC 12');

INSERT INTO CONFERENCES_GB (CONFERENCE_ID, CONFERENCE_NAME)
    VALUES (8, 'SEC');

INSERT INTO CONFERENCES_GB (CONFERENCE_ID, CONFERENCE_NAME)
    VALUES (37, 'Sun Belt');